# Generated by Django 2.1.7 on 2019-04-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom', models.CharField(max_length=15)),
                ('Prénom', models.CharField(max_length=15)),
                ('Age', models.CharField(max_length=10)),
                ('Adresse', models.CharField(max_length=30)),
                ('Niveau', models.CharField(max_length=15)),
                ('Option', models.CharField(max_length=25)),
                ('Matricule', models.CharField(max_length=8)),
                ('Description', models.TextField()),
                ('photos', models.FileField(upload_to='photo')),
            ],
        ),
    ]
